FEAT: Add possibility to classify partial items as valid
globocom/view-port pull request #11
Opened 2022-02-15 21:39 UTC by RicardoDSantos

> # :rocket: PULL REQUEST FEATURE :rocket:
### Description
Feature: add a possibility to consider a partial item as valid. 

### Screenshots
![image](https://user-images.githubusercontent.com/88405293/154152686-12cf7585-cf54-4783-9339-dae9d87d940d.png)

### Build
Check that your PR meets the following requirements:

- [x] Build (`assembleRelease`) was run locally and got no errors
- [x] Proguard passed locally and there are no failures

### Analysis and Conclusion
Some devices has small screen, so the item is never displayed in full, it is necessary to add tolerance feature to solve the problem for these cases. Its common when the device in Landscape

<br/>

2022-02-16 16:32 UTC, rih-carv commented on commons/src/main/java/com/github/globocom/viewport/commons/ViewPortPartialHelper.kt
> +    }
Pensei em uma forma de unificarmos essa parte dos cálculos 🙂
```suggestion
    private fun isVisiblePortionInsideThreshold(
        view: View,
        helper: OrientationHelper,
        threshold: Float
    ): Boolean {
        val viewStart = helper.getDecoratedStart(view)
        val viewEnd = helper.getDecoratedEnd(view)
        val viewSize = helper.getDecoratedMeasurement(view)

        val containerStart = helper.startAfterPadding
        val containerEnd = helper.endAfterPadding

        val visibleStart = viewStart.coerceIn(containerStart..containerEnd)
        val visibleEnd = viewEnd.coerceIn(containerStart..containerEnd)
        val visibleViewSize = visibleEnd - visibleStart
        val visibleProportion = visibleViewSize.toFloat() / viewSize
        return visibleProportion >= threshold
    }
```

2022-02-16 16:32 UTC, rih-carv commented on commons/src/main/java/com/github/globocom/viewport/commons/ViewPortPartialHelper.kt
> +    }
E nessa parte ficaria meio que assim... (incluindo outras alterações que também sugiro, em relação ao `while` e aos parâmetros)
```suggestion
private fun findOneVisibleChild(
        layoutManager: RecyclerView.LayoutManager,
        threshold: Float,
        searchFromEndToStart: Boolean = false
    ): View? {
        val helper: OrientationHelper = if (layoutManager.canScrollVertically()) {
            OrientationHelper.createVerticalHelper(layoutManager)
        } else {
            OrientationHelper.createHorizontalHelper(layoutManager)
        }

        val orderedChildSearch = 0.until(layoutManager.childCount).let {
            if (searchFromEndToStart) it.reversed() else it
        }

        for (index in orderedChildSearch) {
            layoutManager.getChildAt(index)?.let {
                if (isVisiblePortionInsideThreshold(it, helper, threshold))
                    return it
            }
        }
        return null
    }
```

2022-02-16 16:32 UTC, rih-carv commented on commons/src/main/java/com/github/globocom/viewport/commons/ViewPortPartialHelper.kt
> +    }
E aqui poderia ficar assim 🙂
Substituindo os índices pelo `searchFromEndToStart` e utilizando o retorno direto (essa parte é só uma sugestão de estilo, então pode ignorar se quiser 😅, o importante é só os parâmetros mesmo)
```suggestion
    fun findFirstPartiallyVisibleItemPosition(
        recyclerView: RecyclerView,
        linearLayoutManager: LinearLayoutManager,
        threshold: Float = 1f
    ) = findOneVisibleChild(
            linearLayoutManager,
            threshold
        )?.let { childView ->
            recyclerView.getChildAdapterPosition(childView)
        } ?: RecyclerView.NO_POSITION

    fun findLastPartiallyVisibleItemPosition(
        recyclerView: RecyclerView,
        linearLayoutManager: LinearLayoutManager,
        threshold: Float = 1f
    ) = findOneVisibleChild(
            linearLayoutManager,
            threshold,
            true
        )?.let { childView ->
            recyclerView.getChildAdapterPosition(childView)
        } ?: RecyclerView.NO_POSITION
```

2022-02-16 16:59 UTC, rih-carv commented on library-mobile/src/main/java/com/github/globocom/viewport/mobile/ViewPortRecyclerView.kt
> +    }
A função para recriar poderia ser algo meio que assim:
```
internal fun fromProportionValue(proportion: Float) = when (proportion) {
    Visible.proportion -> Visible
    Half.proportion -> Half
    AlmostHidden.proportion -> AlmostHidden
    AlmostVisible.proportion -> AlmostVisible
    else -> Custom(proportion)
}
```
ou assim:
```
internal fun fromProportionValues(proportion: Float) = listOf(
    Visible, Half, AlmostHidden, AlmostVisible
).firstOrNull { it.proportion == proportion } ?: Custom(proportion)
```

2022-02-16 17:14 UTC, rih-carv commented on library-mobile/src/main/java/com/github/globocom/viewport/mobile/ViewPortRecyclerView.kt
> +    }
Ou ao invés de criar a função, podemos ver se conseguimos utilizar a serialização direto como no caso do enum: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes

2022-03-04 20:37 UTC, rih-carv approved these changes

2022-03-04 20:44 UTC, rih-carv approved these changes

2022-03-04 20:57 UTC, rih-carv approved these changes
Niiice 🙂

2022-04-05 19:16 UTC, OBrunoVieira requested changes

2022-04-05 19:16 UTC, OBrunoVieira commented on library-mobile/src/main/java/com/github/globocom/viewport/mobile/Threshold.kt
> +sealed class Threshold(val proportion: Float) {
Com o propósito de tornar mais simples, acho que poderíamos transformar o Threshold para um `enum` ao invés de uma `sealed class`. O que acha?

2022-04-05 19:16 UTC, OBrunoVieira commented on local.properties
> +#Tue Feb 08 09:32:49 BRT 2022
Sugiro removermos o `local.properties` de ser um arquivo remoto e aplicar a regra no .gitignore de ignorá-lo. O que acha?

2022-04-05 19:16 UTC, OBrunoVieira commented on sample/src/main/java/com/github/globocom/viewport/sample/MainActivity.kt
> +        activity_main_spinner_threshold.apply {
como nao estamos fazendo uso do retorno do spinner, sugiro usarmos run ao invés de apply.

2022-04-05 19:16 UTC, OBrunoVieira commented on sample/src/main/java/com/github/globocom/viewport/sample/MainActivity.kt
> +        )
como nao estamos reutilizando esta variavel, sugiro cria-la no momento da refereciação.

2022-04-05 19:16 UTC, OBrunoVieira commented on sample/src/main/java/com/github/globocom/viewport/sample/MainActivity.kt
> +        activity_main_view_port_recycler_view.apply {
nao vejo necessidade do uso do apply aqui, poderíamos chamar a função threshold diretamente.

2022-04-06 13:10 UTC, RicardoDSantos commented on library-mobile/src/main/java/com/github/globocom/viewport/mobile/Threshold.kt
> +sealed class Threshold(val proportion: Float) {
Eu creio que nesse caso nao encaixaria o enum, pois nao existe uma estrutura homogênea neste problema, pois sao 4 valores comuns de uso e um valor de exceção aos demais, o Custom pode assumir um valor dinâmico, podemos até tentar usar enum para representar isso, mas nao vejo uma maneira na qual a classe perderia a coesão ao armazenar o valor por fora da estrutura.

2022-04-06 13:12 UTC, RicardoDSantos commented on local.properties
> +#Tue Feb 08 09:32:49 BRT 2022
ops... concordo hehehe

2022-04-06 19:06 UTC, OBrunoVieira requested changes

2022-04-06 19:06 UTC, OBrunoVieira commented on library-mobile/src/main/java/com/github/globocom/viewport/mobile/Threshold.kt
> +        fun fromProportionValue(proportion: Float) = values().first { it.proportion == proportion }
O método `first` tem um grande problema, se ele nao achar o elemento na lista, ele dispara uma exceção. O resultado direto será refletido no globoplay com o crash. Sendo assim, sugiro uma nova abordagem como por exemplo o uso do `firstOrNull`

2022-04-06 19:06 UTC, OBrunoVieira commented on sample/src/main/java/com/github/globocom/viewport/sample/MainActivity.kt
> +        return Threshold.valueOf(spinnerThresholdValues[activity_main_spinner_threshold.selectedItemPosition])
Se por algum motivo o `activity_main_spinner_threshold.selectedItemPosition` for um index que nao se enquadre ao array, teremos um _**AOOB Exception**_. Sendo assim, sugiro usarmos o `getOrNull`

2022-04-06 19:06 UTC, OBrunoVieira commented on sample/src/main/java/com/github/globocom/viewport/sample/MainActivity.kt
> +        activity_main_view_port_recycler_view.threshold(Threshold.valueOf(spinnerThresholdValues[position]))
> Se por algum motivo o `activity_main_spinner_threshold.selectedItemPosition` for um index que nao se enquadre ao array, teremos um _**AOOB Exception**_. Sendo assim, sugiro usarmos o `getOrNull`

A msma sugestao se aplica pra cá.

2022-04-06 19:09 UTC, RicardoDSantos commented on library-mobile/src/main/java/com/github/globocom/viewport/mobile/Threshold.kt
> +        fun fromProportionValue(proportion: Float) = values().first { it.proportion == proportion }
ops, eu tava usando o first or null, vou forçar um retorno padrao como estava com o selaed.

2022-04-06 19:16 UTC, RicardoDSantos commented on sample/src/main/java/com/github/globocom/viewport/sample/MainActivity.kt
> +        return Threshold.valueOf(spinnerThresholdValues[activity_main_spinner_threshold.selectedItemPosition])
como se trata do sample e temos o exato número de indices, eu nao vou mexer por agora pela urgencia, acho que seria interessante atrelar depois o enum a criação do adapter para ficar "amarrado" as positions.

2022-04-06 19:22 UTC, OBrunoVieira approved these changes

2022-04-06 19:23 UTC, merged